services:
  - type: web
    name: sunwave
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn wsgi:app
    plan: free
    envVars:
      - key: PRODUCTION
        value: true
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 